INDICES EN LISTAS 

In [7]:
a = [422, 34, 654, 231] #Tienen un indice asociado a su posicion en dicha lista
#pos 0,1,2,3,4,...
print(a)
a[0]
a[2]

[422, 34, 654, 231]


654

Añadir Listas 

In [11]:
B = [1, 5, 3, 2, 6, 9]
B.append(0)
print(B)


[1, 5, 3, 2, 6, 9, 0]


In [31]:
C = [] 
C.append([1,4,5,2])
C.append([5,6,2,4])
C.append([3,5,6,2])
print(C)


[[1, 4, 5, 2], [5, 6, 2, 4], [3, 5, 6, 2]]


In [32]:
import numpy as np
C = np.array(C)
print(C)  


[[1 4 5 2]
 [5 6 2 4]
 [3 5 6 2]]


OPERACIONES DE LISTAS 

In [47]:
#print(C[2]) #mostrar segunda lista 
print(C[2][3])  #para mostrar la posicion 3 de la lista 2


2


In [49]:
D = [1,4,3,2,5,4]
print(D)

[1, 4, 3, 2, 5, 4]


In [52]:
suma = sum(D)
print(suma)


19


In [56]:
longitud = len(D)
print(longitud)

6


PROMEDIO DE UN ARREGLO 

In [58]:
promedio = sum(D)/len(D)
print(promedio)


3.1666666666666665


In [63]:
import statistics as st
promedio_2 = st.mean(D)
print(promedio_2)


3.1666666666666665


In [66]:
import statistics
promedio_3 = statistics.mean(D)
print(promedio_3)

3.1666666666666665


LISTA CON STRINGS

In [72]:
string = ["ags", "arjd", "jad", "jsha"]
#print(string) 
print(string[1][2]) #mostrar la posicion 2 de la string 1


j


In [73]:
longitud = len(string)
print(longitud)

4


In [75]:
print(string[2][0:2])

ja


DICCIONARIOS

In [90]:
datos_alumno = {
    'Nombre' :'Martin',
    'Apellido' :'Martinez',
    'Matricula' : '19002312',
    'Horario' : 'Matutino',
    'Beca' : 'NO'
}
print(datos_alumno['Beca'])


NO


In [96]:
datos_alumno.update({'materias': [ 'fisica', 'quimica', 'programacion']})
print(datos_alumno)

{'Nombre': 'Martin', 'Apellido': 'Martinez', 'Matricula': '19002312', 'Horario': 'Matutino', 'Beca': 'NO', 'materias': ['fisica', 'quimica', 'programacion']}


In [99]:
print(datos_alumno['materias'])
print(datos_alumno['materias'][0:2])

['fisica', 'quimica', 'programacion']
['fisica', 'quimica']


DICCIONARIOS ANIDADOS

In [102]:
pacientes = [
    {
     'Nombre':'Cruz',
     'Seguro':'Si',
     'ID_seguro':'128392010',
     'Covid':'Si',
     'G_sanguineo':'AB+'
    },

    {
     'Nombre':'Martin',
     'Seguro':'Si',
     'ID_seguro':'193827432',
     'Covid':'No',
     'G_sanguineo':'A+'
    },

    {
     'Nombre':'Pedro',
     'Seguro':'SI',
     'ID_seguro':'123928381',
     'Covid':'No',
     'G_sanguineo':'B+',
    }
]

print(pacientes[1]['Nombre'])
print(pacientes[1]['Seguro'])
print(pacientes[1]['ID_seguro'])


Martin
Si
193827432
